require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ProvasController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Prova. As you add validations to Prova, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProvasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all provas as @provas" do
      prova = Prova.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:provas)).to eq([prova])
    end
  end

  describe "GET #show" do
    it "assigns the requested prova as @prova" do
      prova = Prova.create! valid_attributes
      get :show, {:id => prova.to_param}, valid_session
      expect(assigns(:prova)).to eq(prova)
    end
  end

  describe "GET #new" do
    it "assigns a new prova as @prova" do
      get :new, {}, valid_session
      expect(assigns(:prova)).to be_a_new(Prova)
    end
  end

  describe "GET #edit" do
    it "assigns the requested prova as @prova" do
      prova = Prova.create! valid_attributes
      get :edit, {:id => prova.to_param}, valid_session
      expect(assigns(:prova)).to eq(prova)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Prova" do
        expect {
          post :create, {:prova => valid_attributes}, valid_session
        }.to change(Prova, :count).by(1)
      end

      it "assigns a newly created prova as @prova" do
        post :create, {:prova => valid_attributes}, valid_session
        expect(assigns(:prova)).to be_a(Prova)
        expect(assigns(:prova)).to be_persisted
      end

      it "redirects to the created prova" do
        post :create, {:prova => valid_attributes}, valid_session
        expect(response).to redirect_to(Prova.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved prova as @prova" do
        post :create, {:prova => invalid_attributes}, valid_session
        expect(assigns(:prova)).to be_a_new(Prova)
      end

      it "re-renders the 'new' template" do
        post :create, {:prova => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested prova" do
        prova = Prova.create! valid_attributes
        put :update, {:id => prova.to_param, :prova => new_attributes}, valid_session
        prova.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested prova as @prova" do
        prova = Prova.create! valid_attributes
        put :update, {:id => prova.to_param, :prova => valid_attributes}, valid_session
        expect(assigns(:prova)).to eq(prova)
      end

      it "redirects to the prova" do
        prova = Prova.create! valid_attributes
        put :update, {:id => prova.to_param, :prova => valid_attributes}, valid_session
        expect(response).to redirect_to(prova)
      end
    end

    context "with invalid params" do
      it "assigns the prova as @prova" do
        prova = Prova.create! valid_attributes
        put :update, {:id => prova.to_param, :prova => invalid_attributes}, valid_session
        expect(assigns(:prova)).to eq(prova)
      end

      it "re-renders the 'edit' template" do
        prova = Prova.create! valid_attributes
        put :update, {:id => prova.to_param, :prova => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested prova" do
      prova = Prova.create! valid_attributes
      expect {
        delete :destroy, {:id => prova.to_param}, valid_session
      }.to change(Prova, :count).by(-1)
    end

    it "redirects to the provas list" do
      prova = Prova.create! valid_attributes
      delete :destroy, {:id => prova.to_param}, valid_session
      expect(response).to redirect_to(provas_url)
    end
  end

end
