require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RespostaalunosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Respostaaluno. As you add validations to Respostaaluno, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RespostaalunosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all respostaalunos as @respostaalunos" do
      respostaaluno = Respostaaluno.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:respostaalunos)).to eq([respostaaluno])
    end
  end

  describe "GET #show" do
    it "assigns the requested respostaaluno as @respostaaluno" do
      respostaaluno = Respostaaluno.create! valid_attributes
      get :show, {:id => respostaaluno.to_param}, valid_session
      expect(assigns(:respostaaluno)).to eq(respostaaluno)
    end
  end

  describe "GET #new" do
    it "assigns a new respostaaluno as @respostaaluno" do
      get :new, {}, valid_session
      expect(assigns(:respostaaluno)).to be_a_new(Respostaaluno)
    end
  end

  describe "GET #edit" do
    it "assigns the requested respostaaluno as @respostaaluno" do
      respostaaluno = Respostaaluno.create! valid_attributes
      get :edit, {:id => respostaaluno.to_param}, valid_session
      expect(assigns(:respostaaluno)).to eq(respostaaluno)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Respostaaluno" do
        expect {
          post :create, {:respostaaluno => valid_attributes}, valid_session
        }.to change(Respostaaluno, :count).by(1)
      end

      it "assigns a newly created respostaaluno as @respostaaluno" do
        post :create, {:respostaaluno => valid_attributes}, valid_session
        expect(assigns(:respostaaluno)).to be_a(Respostaaluno)
        expect(assigns(:respostaaluno)).to be_persisted
      end

      it "redirects to the created respostaaluno" do
        post :create, {:respostaaluno => valid_attributes}, valid_session
        expect(response).to redirect_to(Respostaaluno.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved respostaaluno as @respostaaluno" do
        post :create, {:respostaaluno => invalid_attributes}, valid_session
        expect(assigns(:respostaaluno)).to be_a_new(Respostaaluno)
      end

      it "re-renders the 'new' template" do
        post :create, {:respostaaluno => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested respostaaluno" do
        respostaaluno = Respostaaluno.create! valid_attributes
        put :update, {:id => respostaaluno.to_param, :respostaaluno => new_attributes}, valid_session
        respostaaluno.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested respostaaluno as @respostaaluno" do
        respostaaluno = Respostaaluno.create! valid_attributes
        put :update, {:id => respostaaluno.to_param, :respostaaluno => valid_attributes}, valid_session
        expect(assigns(:respostaaluno)).to eq(respostaaluno)
      end

      it "redirects to the respostaaluno" do
        respostaaluno = Respostaaluno.create! valid_attributes
        put :update, {:id => respostaaluno.to_param, :respostaaluno => valid_attributes}, valid_session
        expect(response).to redirect_to(respostaaluno)
      end
    end

    context "with invalid params" do
      it "assigns the respostaaluno as @respostaaluno" do
        respostaaluno = Respostaaluno.create! valid_attributes
        put :update, {:id => respostaaluno.to_param, :respostaaluno => invalid_attributes}, valid_session
        expect(assigns(:respostaaluno)).to eq(respostaaluno)
      end

      it "re-renders the 'edit' template" do
        respostaaluno = Respostaaluno.create! valid_attributes
        put :update, {:id => respostaaluno.to_param, :respostaaluno => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested respostaaluno" do
      respostaaluno = Respostaaluno.create! valid_attributes
      expect {
        delete :destroy, {:id => respostaaluno.to_param}, valid_session
      }.to change(Respostaaluno, :count).by(-1)
    end

    it "redirects to the respostaalunos list" do
      respostaaluno = Respostaaluno.create! valid_attributes
      delete :destroy, {:id => respostaaluno.to_param}, valid_session
      expect(response).to redirect_to(respostaalunos_url)
    end
  end

end
